# Generated by Django 5.2.6 on 2025-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(blank=True, help_text='Unique animal identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, help_text='Animal breed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='abbatoir_name',
            name='farm_name',
>>>>>>> aa57a1f (Implement weight-based selling and inventory management):meat_trace/migrations/0002_animal_animal_id_animal_breed_animal_farm_name.py
            field=models.CharField(blank=True, help_text='Abbatoir name', max_length=100, null=True),
        ),
    ]
