# Generated by Django 5.2.6 on 2025-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, help_text='Animal health status (e.g., Healthy, Sick, Under Treatment)', max_length=50, null=True),
        ),
    ]
