# Generated by Django 5.2.6 on 2025-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0006_animal_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(blank=True, help_text='Optional custom animal name or tag', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(default='', editable=False, help_text='Auto-generated unique animal identifier', max_length=50, unique=True),
        ),
    ]
