# Generated by Django 5.2.6 on 2025-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0011_carcassmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
