# Generated by Django 5.2.6 on 2025-10-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0012_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='processed',
            field=models.BooleanField(default=False, help_text='Indicates if the animal has been processed into products'),
        ),
    ]
