# Generated by Django 5.2.6 on 2025-10-13 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0013_animal_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, help_text='Age in months', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
