# Generated by Django 5.2.6 on 2025-10-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0014_alter_animal_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
        migrations.AddField(
            model_name='animal',
            name='live_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Live weight in kg before slaughter', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
