# Generated by Django 5.2.6 on 2025-10-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0015_remove_animal_weight_animal_live_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, help_text='Animal photo', null=True, upload_to='animal_photos/'),
        ),
    ]
