# Generated by Django 5.2.6 on 2025-10-13 10:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0016_animal_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('whole_carcass', 'Whole Carcass'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('head', 'Head'), ('feet', 'Feet'), ('internal_organs', 'Internal Organs'), ('other', 'Other')], default='whole_carcass', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of this part in kg', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams')], default='kg', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Additional description of the part', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaughter_parts', to='meat_trace.animal')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parts', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('animal', 'part_type')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='slaughter_part',
            field=models.ForeignKey(blank=True, help_text='The specific slaughter part this product was made from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='meat_trace.slaughterpart'),
        ),
    ]
