# Generated by Django 5.2.6 on 2025-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0017_slaughterpart_product_slaughter_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='abbatoir_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='abbatoir_name',
            field=models.CharField(blank=True, help_text='Abbatoir name', max_length=100, null=True),
        ),
    ]
