# Generated by Django 5.2.6 on 2025-10-13 12:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0019_auto_20251013_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterpart',
            name='used_in_product',
            field=models.BooleanField(default=False, help_text='Indicates if this part has been used to create a product'),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, help_text='Quantity of this part used in the product', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams')], default='kg', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meat_trace.product')),
                ('slaughter_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='meat_trace.slaughterpart')),
            ],
            options={
                'unique_together': {('product', 'slaughter_part')},
            },
        ),
    ]
