# Generated by Django 5.2.6 on 2025-10-15 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0021_shop_userprofile_shop_alter_inventory_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcassmeasurement',
            name='carcass_type',
            field=models.CharField(choices=[('whole', 'Whole Carcass'), ('half', 'Half Carcass'), ('quarter', 'Quarter Carcass'), ('other', 'Other')], default='whole', help_text='Type of carcass measurement', max_length=20),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='left_side_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of left side', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='right_side_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of right side', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total carcass weight', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams')], default='kg', help_text='Unit for weight measurements', max_length=10),
        ),
    ]
