# Generated by Django 5.2.6 on 2025-10-15 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0022_carcassmeasurement_carcass_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcassmeasurement',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='feet_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of feet', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='head_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of head', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='internal_organs_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of internal organs', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='torso_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of torso', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='carcass_type',
            field=models.CharField(choices=[('whole', 'Whole Carcass'), ('split', 'Split Carcass')], default='whole', help_text='Type of carcass measurement', max_length=20),
        ),
    ]
