# Generated by Django 5.2.6 on 2025-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0024_alter_carcassmeasurement_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='measurements',
            field=models.JSONField(blank=True, help_text="JSON object containing measurement data: {'head_weight': {'value': 5.2, 'unit': 'kg'}, 'torso_weight': {'value': 45.8, 'unit': 'kg'}}"),
        ),
    ]
