# Generated by Django 5.2.6 on 2025-10-15 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0025_alter_carcassmeasurement_measurements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processingunituser',
            name='granular_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object defining specific permissions'),
        ),
        migrations.AddField(
            model_name='processingunituser',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether the user is currently suspended'),
        ),
        migrations.AddField(
            model_name='processingunituser',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time user was active in the system', null=True),
        ),
        migrations.AddField(
            model_name='processingunituser',
            name='suspension_date',
            field=models.DateTimeField(blank=True, help_text='Date when user was suspended', null=True),
        ),
        migrations.AddField(
            model_name='processingunituser',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension', null=True),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_invited', 'User Invited'), ('user_joined', 'User Joined'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('user_removed', 'User Removed'), ('role_changed', 'Role Changed'), ('permissions_changed', 'Permissions Changed'), ('granular_permissions_changed', 'Granular Permissions Changed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('security_event', 'Security Event')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action performed')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values before the change')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after the change')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context or metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='meat_trace.processingunit')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='meat_trace.shop')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['performed_by', 'timestamp'], name='meat_trace__perform_7e7a55_idx'), models.Index(fields=['affected_user', 'timestamp'], name='meat_trace__affecte_ea69ea_idx'), models.Index(fields=['processing_unit', 'timestamp'], name='meat_trace__process_7a4dcb_idx'), models.Index(fields=['shop', 'timestamp'], name='meat_trace__shop_id_8999ef_idx'), models.Index(fields=['action', 'timestamp'], name='meat_trace__action_91dbcb_idx')],
            },
        ),
    ]
