# Generated by Django 5.2.6 on 2025-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0027_userprofile_address_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_animals', to='meat_trace.processingunit'),
        ),
    ]
