# Generated by Django 5.2.6 on 2025-10-18 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0028_alter_animal_transferred_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('registration', 'Animal Registration'), ('transfer', 'Animal Transfer'), ('slaughter', 'Animal Slaughter'), ('health_update', 'Health Status Update'), ('weight_update', 'Weight Update'), ('vaccination', 'Vaccination'), ('other', 'Other Activity')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the related entity (animal, batch, etc.)', max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity (animal, batch, etc.)', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('target_route', models.CharField(blank=True, help_text='Route to navigate when activity is clicked', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='meat_trace__timesta_da206c_idx'), models.Index(fields=['activity_type'], name='meat_trace__activit_8189ad_idx')],
            },
        ),
    ]
