# Generated by Django 5.2.6 on 2025-10-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0029_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterpart',
            name='is_selected_for_transfer',
            field=models.BooleanField(default=False, help_text='Whether this part is selected for the current transfer'),
        ),
        migrations.AlterField(
            model_name='slaughterpart',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_parts', to='meat_trace.processingunit'),
        ),
    ]
