# Generated by Django 5.2.6 on 2025-10-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0030_slaughterpart_is_selected_for_transfer_and_more'),
    ]

    operations = [
        # Rename fields to align with frontend expectations
        migrations.RenameField(
            model_name='carcassmeasurement',
            old_name='left_side_weight',
            new_name='front_legs_weight',
        ),
        migrations.RenameField(
            model_name='carcassmeasurement',
            old_name='right_side_weight',
            new_name='hind_legs_weight',
        ),
        migrations.RenameField(
            model_name='carcassmeasurement',
            old_name='internal_organs_weight',
            new_name='organs_weight',
        ),
        # feet_weight stays as is - both backend and frontend use the same name
    ]
