# Generated by Django 5.2.6 on 2025-10-19 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0031_align_carcass_measurement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='front_legs_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of front legs', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='hind_legs_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of hind legs', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='organs_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of organs', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
