# Generated by Django 5.2.6 on 2025-10-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0033_backupschedule_systemhealth_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Animal gender', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the animal', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_products', to='meat_trace.processingunit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('abbatoir', 'Abbatoir'), ('processing_unit', 'Processing Unit'), ('shop', 'Shop')], default='abbatoir', max_length=20),
        ),
    ]
