# Generated by Django 5.2.6 on 2025-10-22 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0034_animal_gender_animal_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=20)),
                ('batch_number', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_code_url', models.CharField(blank=True, max_length=500, null=True)),
                ('processing_unit_name', models.CharField(blank=True, max_length=200, null=True)),
                ('processing_unit_location', models.CharField(blank=True, max_length=200, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('animal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_species', models.CharField(blank=True, max_length=20, null=True)),
                ('abbatoir_username', models.CharField(blank=True, max_length=150, null=True)),
                ('animal_live_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('animal_slaughtered', models.BooleanField(default=False)),
                ('animal_slaughtered_at', models.DateTimeField(blank=True, null=True)),
                ('animal_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('animal_transferred_to_name', models.CharField(blank=True, max_length=200, null=True)),
                ('timeline_events', models.JSONField(blank=True, default=list)),
                ('inventory_count', models.IntegerField(default=0)),
                ('receipts_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('carcass_measurement_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='meat_trace.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
