# Generated by Django 5.2.6 on 2025-10-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0036_change_product_received_by_to_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_products', to='meat_trace.shop'),
        ),
    ]
