# Generated by Django 5.2.6 on 2025-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0038_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterpart',
            name='part_id',
            field=models.CharField(default='', editable=False, help_text='Auto-generated unique part identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='slaughterpart',
            name='part_type',
            field=models.CharField(choices=[('whole_carcass', 'Whole Carcass'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('head', 'Head'), ('feet', 'Feet'), ('internal_organs', 'Internal Organs'), ('torso', 'Torso'), ('front_legs', 'Front Legs'), ('hind_legs', 'Hind Legs')], default='whole_carcass', max_length=20),
        ),
    ]
