# Generated by Django 5.2.6 on 2025-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0039_slaughterpart_part_id_alter_slaughterpart_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcassmeasurement',
            name='whole_carcass_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of whole carcass', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='feet_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of feet', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carcassmeasurement',
            name='head_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of head', max_digits=10, null=True),
        ),
    ]
