# Generated by Django 5.2.6 on 2025-11-05 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0040_carcassmeasurement_whole_carcass_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcassmeasurement',
            name='front_legs_weight',
        ),
        migrations.RemoveField(
            model_name='carcassmeasurement',
            name='hind_legs_weight',
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='left_carcass_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of left carcass', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='carcassmeasurement',
            name='right_carcass_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of right carcass', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='slaughterpart',
            name='part_type',
            field=models.CharField(choices=[('whole_carcass', 'Whole Carcass'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('left_carcass', 'Left Carcass'), ('right_carcass', 'Right Carcass'), ('head', 'Head'), ('feet', 'Feet'), ('internal_organs', 'Internal Organs'), ('torso', 'Torso'), ('front_legs', 'Front Legs'), ('hind_legs', 'Hind Legs')], default='whole_carcass', max_length=20),
        ),
    ]
