# Generated by Django 5.2.6 on 2025-11-06 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0041_remove_carcassmeasurement_front_legs_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='appeal_notes',
            field=models.TextField(blank=True, help_text='Notes about the appeal', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='appeal_resolved_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the appeal was resolved', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='appeal_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('resolved', 'Resolved')], help_text='Current appeal status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='appealed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the appeal was submitted', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the animal was rejected', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the animal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the rejection', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejection_reason_category',
            field=models.CharField(blank=True, help_text='Category of rejection reason', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejection_reason_specific',
            field=models.CharField(blank=True, help_text='Specific rejection reason', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('resolved', 'Resolved')], help_text='Current rejection status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='appeal_notes',
            field=models.TextField(blank=True, help_text='Notes about the appeal', null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='appeal_resolved_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the appeal was resolved', null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='appeal_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('resolved', 'Resolved')], help_text='Current appeal status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='appealed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the appeal was submitted', null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the part was rejected', null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the rejection', null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejection_reason_category',
            field=models.CharField(blank=True, help_text='Category of rejection reason', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejection_reason_specific',
            field=models.CharField(blank=True, help_text='Specific rejection reason', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('resolved', 'Resolved')], help_text='Current rejection status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('join_approved', 'Join Request Approved'), ('join_rejected', 'Join Request Rejected'), ('invitation', 'User Invitation'), ('role_change', 'Role Changed'), ('profile_update', 'Profile Update Required'), ('verification', 'Account Verification'), ('animal_rejected', 'Animal Rejected'), ('part_rejected', 'Slaughter Part Rejected'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_approved', 'Appeal Approved'), ('appeal_denied', 'Appeal Denied')], max_length=30),
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quality', 'Quality Issues'), ('documentation', 'Documentation Issues'), ('health_safety', 'Health & Safety'), ('compliance', 'Compliance Issues'), ('logistics', 'Logistics Issues'), ('other', 'Other')], max_length=20)),
                ('specific_reason', models.CharField(choices=[('poor_condition', 'Poor Physical Condition'), ('contamination', 'Contamination'), ('incorrect_weight', 'Incorrect Weight'), ('damage', 'Physical Damage'), ('expired', 'Expired/Outdated'), ('missing_docs', 'Missing Documentation'), ('invalid_docs', 'Invalid Documentation'), ('incomplete_records', 'Incomplete Records'), ('wrong_animal', 'Wrong Animal ID'), ('disease_symptoms', 'Disease Symptoms'), ('parasites', 'Parasites/Insects'), ('chemical_residues', 'Chemical Residues'), ('temperature_issues', 'Temperature Issues'), ('certification_missing', 'Missing Certification'), ('traceability_breach', 'Traceability Breach'), ('regulatory_violation', 'Regulatory Violation'), ('transport_damage', 'Transport Damage'), ('delayed_delivery', 'Delayed Delivery'), ('packaging_issues', 'Packaging Issues'), ('other', 'Other (Specify in Notes)')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rejection', null=True)),
                ('rejected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='meat_trace.animal')),
                ('processing_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='meat_trace.processingunit')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
                ('slaughter_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='meat_trace.slaughterpart')),
            ],
            options={
                'ordering': ['-rejected_at'],
                'indexes': [models.Index(fields=['animal', 'rejected_at'], name='meat_trace__animal__63e705_idx'), models.Index(fields=['slaughter_part', 'rejected_at'], name='meat_trace__slaught_9240f5_idx'), models.Index(fields=['category', 'rejected_at'], name='meat_trace__categor_d1b96d_idx'), models.Index(fields=['processing_unit', 'rejected_at'], name='meat_trace__process_7e65f5_idx')],
            },
        ),
    ]
