# Generated by Django 5.2.6 on 2025-11-07 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0042_animal_appeal_notes_animal_appeal_resolved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('view', 'View Details'), ('approve', 'Approve'), ('reject', 'Reject'), ('respond', 'Respond'), ('appeal', 'Appeal')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, help_text='Groups related notifications together', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_batch_notification',
            field=models.BooleanField(default=False, help_text='Indicates if this is part of a batch notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='meat_trace__user_id_a599d0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='meat_trace__user_id_9771c9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_dismissed'], name='meat_trace__user_id_d05105_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_archived'], name='meat_trace__user_id_87076c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='meat_trace__priorit_8378e3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key', 'created_at'], name='meat_trace__group_k_73776b_idx'),
        ),
    ]
