# Generated by Django 5.2.6 on 2025-11-08 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0043_add_notification_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='remaining_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining weight available for product creation', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='slaughterpart',
            name='remaining_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining weight available for product creation', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
