# Generated by Django 5.2.6 on 2025-11-08 02:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0044_animal_remaining_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity actually received by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_rejected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity rejected by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the product was rejected', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected')], help_text='Current rejection status', max_length=20, null=True),
        ),
    ]
