# Generated by Django 5.2.6 on 2025-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0045_add_product_receipt_and_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Abbatoir', 'Abbatoir'), ('Processor', 'Processor'), ('ShopOwner', 'Shop Owner'), ('Admin', 'Administrator')], default='Abbatoir', max_length=20),
        ),
    ]
