# Generated by Django 5.2.6 on 2025-11-13 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0046_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Configuration key (e.g., 'database.connection_pool.max_size')", max_length=255, unique=True)),
                ('value', models.TextField(help_text='Current configuration value')),
                ('default_value', models.TextField(blank=True, help_text='Default value if not set', null=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('database', 'Database'), ('cache', 'Cache'), ('logging', 'Logging'), ('monitoring', 'Monitoring'), ('security', 'Security'), ('api', 'API'), ('notification', 'Notification')], default='general', max_length=20)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON validation rules (min, max, required, etc.)')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this config contains sensitive data')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this config requires system restart')),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for organization')),
                ('version', models.PositiveIntegerField(default=1, help_text='Current version number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rollback', 'Rolled Back')], max_length=20)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(help_text='Version number at time of change')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change', null=True)),
                ('validation_status', models.CharField(default='passed', help_text='Validation status of the change', max_length=20)),
                ('rollback_available', models.BooleanField(default=True, help_text='Whether this change can be rolled back to')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_changes', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='meat_trace.systemconfiguration')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(help_text='Unique identifier for the feature flag', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('scheduled', 'Scheduled')], default='disabled', max_length=20)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('target_audience', models.JSONField(default=dict, help_text='\n    Targeting rules: {\n        "type": "percentage|user_list|user_segments|all_users",\n        "percentage": 50,  # for percentage type\n        "user_ids": [1,2,3],  # for user_list type\n        "user_segments": ["admins", "farmers"],  # for user_segments type\n        "excluded_users": [4,5]  # users to exclude\n    }\n    ')),
                ('rollout_schedule', models.JSONField(blank=True, default=dict, help_text='\n    Rollout schedule: {\n        "start_date": "2025-11-01T00:00:00Z",\n        "end_date": null,\n        "gradual_rollout": true,\n        "rollout_percentage_per_day": 10\n    }\n    ')),
                ('kill_switch_enabled', models.BooleanField(default=True, help_text='Whether this flag can be quickly disabled')),
                ('monitoring_enabled', models.BooleanField(default=True, help_text='Whether usage is being monitored')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of feature flag keys this depends on')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organization')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['key'], name='meat_trace__key_72f36b_idx'), models.Index(fields=['status', 'environment'], name='meat_trace__status_9c1472_idx'), models.Index(fields=['created_at'], name='meat_trace__created_fd11d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['category', 'environment'], name='meat_trace__categor_7bcb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['key'], name='meat_trace__key_fb79df_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['is_sensitive'], name='meat_trace__is_sens_789be7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['requires_restart'], name='meat_trace__require_349797_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['configuration', 'changed_at'], name='meat_trace__configu_b66bee_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['action', 'changed_at'], name='meat_trace__action_6fee81_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['changed_by', 'changed_at'], name='meat_trace__changed_77a5d0_idx'),
        ),
    ]
