# Generated by Django 5.2.6 on 2025-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0048_notificationchannel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, default='healthy', help_text='Animal health status (e.g., healthy, sick, injured, quarantine)', max_length=50),
        ),
    ]
