# Generated by Django 5.2.6 on 2025-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0049_update_health_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingunit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the processing unit is active and accepting registrations'),
        ),
    ]
