# Generated by Django 5.2.6 on 2026-01-27 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0053_inventory_weight_inventory_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight actually received by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_rejected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight rejected by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
