# Generated by Django 6.0.1 on 2026-01-27 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0053_inventory_weight_inventory_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='weight_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight actually received by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_rejected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight rejected by shop', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='processing_unit',
            field=models.ForeignKey(blank=True, help_text='Processing unit this category belongs to (null for legacy global categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='meat_trace.processingunit'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'processing_unit')},
        ),
    ]
