# Generated by Django 6.0.1 on 2026-01-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0054_add_processing_unit_to_productcategory'),
        ('meat_trace', '0054_product_weight_received_product_weight_rejected'),
    ]

    operations = [
    ]
