# Generated by Django 6.0.1 on 2026-01-28 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0055_merge_20260128_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
