# Generated by Django 6.0.1 on 2026-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0056_sale_receipt_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price paid for external acquisition', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_vendor_id',
            field=models.IntegerField(blank=True, help_text='Reference to ExternalVendor ID if applicable', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_vendor_name',
            field=models.CharField(blank=True, help_text='Name of the external vendor', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_external_source',
            field=models.BooleanField(default=False, help_text='Whether this product was acquired from an external vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining weight available in stock (mostly for external items)', max_digits=10, null=True),
        ),
    ]
