# Generated by Django 6.0.1 on 2026-02-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0058_alter_animal_abbatoir_alter_product_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(default='', help_text='Auto-generated unique animal identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='processing_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='meat_trace.processingunit'),
        ),
    ]
