# Generated by Django 6.0.1 on 2026-02-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0060_alter_receipt_options_receipt_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepayment',
            old_name='reference_number',
            new_name='transaction_reference',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
    ]
