# Generated by Django 6.0.1 on 2026-02-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0061_rename_reference_number_invoicepayment_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='currency',
            field=models.CharField(default='TZS', help_text='Default currency (e.g., TZS, USD, KES)', max_length=10),
        ),
    ]
