# Generated by Django 6.0.1 on 2026-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0062_shopsettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
