# Generated by Django 6.0.1 on 2026-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0063_invoice_customer_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_ref',
            field=models.CharField(blank=True, help_text='Customer reference number/ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='tax_id',
            field=models.CharField(blank=True, help_text="Shop's TIN/Tax ID", max_length=50, null=True),
        ),
    ]
