# Generated by Django 6.0.1 on 2026-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0064_invoice_customer_ref_shopsettings_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
