# Generated by Django 6.0.1 on 2026-04-18 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0065_shopsettings_bank_branch_shopsettings_swift_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('evisceration', 'Evisceration Loss'), ('processing', 'Processing Loss'), ('rejection', 'Rejection Loss'), ('trimming', 'Trimming Loss'), ('spoilage', 'Spoilage'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('abbatoir', 'Abbatoir'), ('processing_unit', 'Processing Unit'), ('shop', 'Shop')], default='abbatoir', help_text='Where in the pipeline the waste was observed', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Waste weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Expected weight before this stage (e.g. live_weight)', max_digits=10, null=True)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Observed weight after this stage (e.g. carcass total)', max_digits=10, null=True)),
                ('auto_generated', models.BooleanField(default=False, help_text='True when created by the system from a measurement delta')),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('abbatoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbatoir_waste', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='meat_trace.animal')),
                ('processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='meat_trace.processingunit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='meat_trace.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_waste', to=settings.AUTH_USER_MODEL)),
                ('slaughter_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='meat_trace.slaughterpart')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['waste_type'], name='meat_trace__waste_t_4466ec_idx'), models.Index(fields=['stage', '-recorded_at'], name='meat_trace__stage_855eb1_idx'), models.Index(fields=['animal'], name='meat_trace__animal__103caf_idx')],
            },
        ),
    ]
