# Generated by Django 6.0.4 on 2026-07-02 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0066_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Animal date of birth; when set, age is derived from it', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, help_text='Age in months at registration', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
