# Generated by Django 5.2.6 on 2026-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_trace', '0069_backfill_weight_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('resolved', 'Resolved')], db_index=True, help_text='Current rejection status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slaughtered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='slaughterpart',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('resolved', 'Resolved')], db_index=True, help_text='Current rejection status', max_length=20, null=True),
        ),
    ]
